### PR TITLE
[wip] SOCKS support, take 3

### PR DESCRIPTION
**Pull request by Anorov**
**[WIP]**

Here is an attempt at SOCKS support with the latest version of PySocks. At the moment there are no tests, though I plan to add them, and definitely encourage others to add them and help with them. I've been testing it with a local script so far. The functionality should all work at the moment, but I can't say that with serious confidence until full tests have been added.

I had to choose between peppering ProxyManager with a few if-branches, or subclassing it and making a SOCKSProxyManager. I decided to go with the former, to preserve full backwards compatibility and allow end users to use the familiar `ProxyManager("socks5://localhost:9050")` syntax. A way to make it more OO while preserving compatibility would be to add override __new__ for ProxyManager and defer to the SOCKSProxyManager class when a SOCKS URL scheme is seen, but it's debatable whether that is more or less Pythonic.

Unfortunately, a pure-Python SOCKS4 and SOCKS5 server may not be feasible for testing, unless someone has one already written. The ones I found on the Internet have various issues. This is why I've held off on comitting anything since then, and frankly didn't want to spend the time hunting around to get a full test suite working. So, test assistance is very much needed.

I am not interested in the bounty, and would like it split between the other contributors.

### CODE REVIEW

**Comment by Anorov** [comment]
Travis appears to be passing on everything at the moment, except for lack of test coverage.

**Comment by gardner** [comment]
Why didn't you write the tests first?

**Comment by Anorov** [comment]
@gardner In the past, I've had severe issues finding a working Python-only SOCKS4 and SOCKS5 server implementation for testing. urllib3 only allows pure-Python code in its test suite.

This has prevented me from making this contribution previously. I decided I should at least get the code committed this time, instead of delaying everything by trying to make a good test suite.

What I will do is write the client part of the test code within the next few days, and hope others will have better luck finding or writing corresponding server code.

**Comment by gardner** [comment]
@Anorov props for getting the functionality there, but from looking at the other pull requests, lack of tests is why this merge has failed in the past. Check out the PySocks tests. You could probably add pure python socks4 pretty easy: https://github.com/Anorov/PySocks/blob/master/test/socks4server.py

**Comment by Anorov** [comment]
@gardner Indeed, that uses Twisted's SOCKS4 server, which is known to be pretty well-written and reliable. Unfortunately, they never released a SOCKS5 server, and every Python SOCKS5 server I hunted for around 2012-2014 proved to have serious issues. That's why I use a non-Python SOCKS5 server for PySocks testing.

Admittedly, I haven't looked in about a year, so I'll see if a good SOCKS5 server implementation exists anywhere.

And yes, the biggest barrier here is definitely the testing, not the code itself. I'll at least keep this code up-to-date with the master branch while the test code is completed.

**Comment by shazow** [comment]
How feasible would it be to do socket-level tests for socks5?

@Lukasa, any ideas?

**Comment by shazow** [comment]
@Anorov We'd like to keep our HTTPConnection things unaware of proxies if possible. Ideally the SOCKS functionality should be contained within ProxyManager or similar. Are there inherent challenges with this?

**Comment by shazow** [comment]
Some suggestions that I think will help get this merged quicker:

- Can we unvendor pysocks for now? We can require it as a proper dependency with the urllib3[socks] extra.
- Until we have tests, let's untangle as much of the logic as possible and put it into urllib3/contrib/socks.py, I will be willing to merge this without full coverage. Only make the absolute minimum changes to the urllib3 core to support this.

**Comment by Anorov** [comment]
@shazow I can certainly "untangle" most everything in connection.py into a separate module. As for all the other changes, I think abstracting out the changes made to `HTTPConnectionPool` and `ProxyManager` may result in unnecessary duplication of code, but I will attempt it and see how it looks. In one way or another, `HTTPConnection`, `HTTPConnectionPool`, and `ProxyManager` will have to modified, be it through subclassing, or the few conditionals I added. There isn't a way to completely isolate the changes to the proxy manager.

I'm certainly open to specific structure suggestions from anyone reading this PR. If anyone sees a way of making things more modular, please provide your input.

As for moving the code to `contrib` from `packages`, I don't really understand what difference it would make. In what ways are non-vendored libraries treated differently?

If you mean it should essentially be considered a third party addon, I would personally rather get this fully completed and committed rather than merging a "user beware" version with missing test coverage. Anyone who needs the SOCKS support right now can simply pull my branch and use it, and IMO that's sufficient for now.

**Comment by shazow** [comment]
> If your contrib suggestion means it should essentially be considered a third party addon, I would personally rather get this fully completed and committed rather than merging a "user beware" version with missing test coverage.

urllib3 core requires 100% test coverage, the contrib sub-package is exempt from that. Yes, it's somewhat a "user beware" thing, but at least it will get more people using it and giving us feedback.

> Anyone who needs the SOCKS support right now can simply pull my branch and use it, and IMO that's sufficient for now.

Unfortunately that's not sufficient, people want to pip install and be done with it. I don't want to explain to dozens of people asking for this how to use git, etc.

>  If this gets caught in limbo again and it's a matter of no support vs. some support, I'd be ok with moving it all to contrib, but I'd like to at least have a week to work on it first.

That's fine if that's what you'd prefer. All I'm suggesting is start in contrib and move it out once we're ready, hopefully soon after. Based on our last 3 attempts, trying to do it "the right way" from the start hasn't proven to be successful. Once it's in contrib with *some* tests, the urllib3 core team will make sure to keep it up to date with the evolution of urllib3's API.

> Assuming full test coverage is finished in the near future, would you still want as much of the additions as possible to be added to a contrib module? Or a socks module in util? Or no new files at all? I think I'm a bit confused as to whether your untangling suggestion is just for the purposes of getting this out there faster, or if it's a general suggestion.

I believe we'll get the best design and fastest iteration if we *start* in the contrib module as decoupled as possible. If you have strong objections, we can do it a different way. :)

> I'm not familiar with install tags or what you mean by urllib3[socks]. How would that be added?

It's a special field in setup.py: https://pythonhosted.org/setuptools/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies

> Do you prefer class names to use Socks or SOCKS? The protocol is called SOCKS, and since urllib3's convention seems to be to capitalize HTTP (rather than using Http) everywhere, for consistency I think SOCKS makes more sense, even though it makes the class name a bit harder to read.

You're right, SOCKS is more consistent.

> Would you be ok with adding Twisted as a test dependency?

I would prefer to avoid it if possible. Ideally we'd use [socket-level tests](https://github.com/shazow/urllib3/blob/master/test/with_dummyserver/test_socketlevel.py). Also @lukasa has been talking about migrating our tests back to twisted (as they were circa 2009), so maybe that's an excuse to do both.

File: urllib3/connection.py [hunk 1]
```diff
@@ -260,9 +266,40 @@ def connect(self):
...
+    """
+    Identical to :class:`HTTPConnection`, except overrides :meth:`socket.create_connection` with
+    :meth:`socks.create_connection`, using ``socks_opts`` arguments from ``**conn_kw`` to
+    construct the :class:`socks.socksocket` object.
+    """
+    def __init__(self, *args, **kw):
+        self.socks_opts = kw.pop('socks_opts', None)
+        super(SOCKSHTTPConnection, self).__init__(*args, **kw)
+
+    def _create_connection(self, address, timeout, **kw):
```
Comment (shazow) [inline urllib3/connection.py]: Might be time to add an interface for providing a create_connection callable, rather than making every protocol adjustment override these methods.

**Comment by Lukasa** [comment]
Re socket-level tests, the SOCKS protocol is pretty well specced ([RFC 1928](https://www.ietf.org/rfc/rfc1928.txt)), so I think we could probably do it. I'd be happy to tackle that in a couple of weeks though as a separate chunk of work to this if @Anorov doesn't want to handle it.

**Comment by Anorov** [comment]
@shazow Makes sense, and I agree. I'll move all the changes to contrib, though ideally I don't want it to be there for too long.

@Lukasa Yeah, writing a small SOCKS server (2 servers in this case, one for SOCKS4 and one for SOCKS5) isn't hard or anything, I frankly just don't want to bother with it.

**Comment by lorien** [comment]
I've tried this branch https://github.com/Anorov/urllib3/tree/socks-support

Does not work on python3.4 The code

```
from urllib3 import PoolManager

pool = PoolManager()
print(pool.urlopen('GET', 'http://ya.ru/robots.txt'))
```
throws Exception

```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    print(pool.urlopen('GET', 'http://ya.ru/robots.txt'))
  File "/home/lorien/web/socks/.env/src/urllib3/urllib3/poolmanager.py", line 162, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/lorien/web/socks/.env/src/urllib3/urllib3/connectionpool.py", line 577, in urlopen
    body=body, headers=headers)
  File "/home/lorien/web/socks/.env/src/urllib3/urllib3/connectionpool.py", line 371, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.4/http/client.py", line 1090, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1086, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 924, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 859, in send
    self.connect()
  File "/home/lorien/web/socks/.env/src/urllib3/urllib3/connection.py", line 161, in connect
    conn = self._new_conn()
  File "/home/lorien/web/socks/.env/src/urllib3/urllib3/connection.py", line 140, in _new_conn
    self.timeout, **extra_kw)
TypeError: create_connection() got an unexpected keyword argument 'socket_options'
```

On python2 this code works as expected.

**Comment by shazow** [comment]
@Anorov Are you still planning on completing this?

**Comment by jbrockmendel** [comment]
I got this working following the example in the docstring to the poolmanager.ProxyManager class.  I had to change the constructor argument from "http://localhost:port" to "socks5://localhost:port".  What I ran:

    >>> # First test the proxy with a urllib2+sockshandler approach that I know works 
    >>> import urllib2, sockshandler
    >>> port = 37076
    >>> lib2handler = sockshandler.SocksiPyHandler(socks.PROXY_TYPE_SOCKS5, "localhost", port)
    >>> opener = urllib2.build_opener(lib2handler)
    >>> page = opener.open('http://httpbin.org/ip')
    >>> page.read()
    '{\n  "origin": "[redacted]"\n}\n'
    >>> # This is the correct IP
    ...
    >>> page.close()
    >>>
    >>> import urllib3
    >>> proxy = urllib3.ProxyManager('http://localhost:37076')
    >>> r = proxy.request('GET', 'http://httpbin.org/ip')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "urllib3/request.py", line 68, in request
        **urlopen_kw)
      File "urllib3/request.py", line 89, in request_encode_url
        return self.urlopen(method, url, **extra_kw)
      File "urllib3/poolmanager.py", line 286, in urlopen
        return super(ProxyManager, self).urlopen(method, url, redirect=redirect, **kw)
      File "urllib3/poolmanager.py", line 160, in urlopen
        response = conn.urlopen(method, url, **kw)
      File "urllib3/connectionpool.py", line 647, in urlopen
        release_conn=release_conn, **response_kw)
      File "urllib3/connectionpool.py", line 647, in urlopen
        release_conn=release_conn, **response_kw)
      File "urllib3/connectionpool.py", line 647, in urlopen
        release_conn=release_conn, **response_kw)
      File "urllib3/connectionpool.py", line 627, in urlopen
        _stacktrace=sys.exc_info()[2])
      File "urllib3/util/retry.py", line 271, in increment
        raise MaxRetryError(_pool, url, error or ResponseError(cause))
    urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=37076): Max retries exceeded with url: http://httpbin.org/ip (Caused by ProtocolError('Connection aborted.', BadStatusLine("''",)))
    >>>
    >>> proxy = urllib3.ProxyManager('socks5://localhost:37076')
    >>> r = proxy.request('GET', 'http://httpbin.org/ip')
    >>> r.data
    '{\n  "origin": "[redacted]"\n}\n'
    >>> # This is the correct IP.

**Comment by shazow** [comment]
Obsoleted by #762
