### ISSUE TITLE
AttributeError: 'module' object has no attribute 'epoll'

### ISSUE THREAD

**Issue by neiljerram** [shazow/urllib3#1104]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/eventlet/hubs/poll.py", line 115, in wait
    listener.cb(fileno)
  File "/usr/local/lib/python2.7/dist-packages/eventlet/greenthread.py", line 214, in main
    result = function(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/networking_calico/agent/dhcp_agent.py", line 553, in loop
    super(SubnetWatcher, self).loop()
  File "/usr/local/lib/python2.7/dist-packages/networking_calico/logutils.py", line 21, in wrapped
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/networking_calico/etcdutils.py", line 250, in loop
    response = self.wait_for_etcd_event()
  File "/usr/local/lib/python2.7/dist-packages/networking_calico/etcdutils.py", line 344, in wait_for_etcd_event
    timeout=self.etcd_timeout)
  File "/usr/local/lib/python2.7/dist-packages/etcd/client.py", line 562, in read
    timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/etcd/client.py", line 820, in wrapper
    params=params, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/etcd/client.py", line 890, in api_execute
    preload_content=False)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/request.py", line 66, in request
    **urlopen_kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/request.py", line 87, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 588, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 241, in _get_conn
    if conn and is_connection_dropped(conn):
  File "/usr/local/lib/python2.7/dist-packages/urllib3/util/connection.py", line 27, in is_connection_dropped
    return bool(wait_for_read(sock, timeout=0.0))
  File "/usr/local/lib/python2.7/dist-packages/urllib3/util/wait.py", line 33, in wait_for_read
    return _wait_for_io_events(socks, EVENT_READ, timeout)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/util/wait.py", line 22, in _wait_for_io_events
    with DefaultSelector() as selector:
  File "/usr/local/lib/python2.7/dist-packages/urllib3/util/selectors.py", line 364, in __init__
    self._epoll = select.epoll()
AttributeError: 'module' object has no attribute 'epoll'

**Comment by neiljerram** [comment]
Hi urllib3 wranglers!  I'm seeing the traceback above in an OpenStack application that uses urllib3.  I found my way to #1001, which feels relevant, and have checked that the OpenStack install is using urllib3 1.20, whose release notes say that it includes that PR.

So I think what I'm seeing is: new version of urllib3 tries to use select.epoll, but for some reason select.epoll is not available.  Can you advise where I should look next to understand this?

**Comment by haikuginger** [comment]
Hi @neiljerram! `select` can behave differently on different platforms, so can we get some more details about your particular environment? Specific OS and Python versions would be great.

**Comment by neiljerram** [comment]
Thanks @haikuginger.  I believe Python is 2.7 (from the paths above - but will double check).  OS should be Ubuntu Xenial, but again I will double check and confirm shortly.

**Comment by neiljerram** [comment]
Also I should say that I believe the same combo (app + Python + OS) was working with urllib3 <1.20 - but I will double check that too.

**Comment by nateprewitt** [comment]
I haven't verified this, but a quick hunch is this is purely an issue with eventlet. They have a module named [select.py](https://github.com/eventlet/eventlet/blob/master/eventlet/green/select.py), which does not have a poll method. That's probably causing issues because it has higher precedence on the path.

**Comment by neiljerram** [comment]
@nateprewitt Ah, yes, the app is using eventlet too.

@haikuginger Definitely Python 2.7, definitely Ubuntu Xenial.

**Comment by neiljerram** [comment]
@haikuginger Also confirmed that my last two successful runs were using urllib3 1.19.1

**Comment by SethMichaelLarson** [comment]
If there's a module called `select.py` in the path higher than the stdlib that would definitely cause an issue. It's strange that it's not erroring out by saying there's no selector available though. Somehow it's detecting that you have `select.epoll` available and then the path is changed before using.

I think I've already got a patch in my head about how to fix this.

**Comment by neiljerram** [comment]
@SethMichaelLarson I'm afraid I'm not following the exact module path issues, but I would be happy to try out your patch...  (I thought Python modules were namespaced, so it would be eventlet.select, urllib3.select, and there would be no ambiguity.)

**Comment by SethMichaelLarson** [comment]
@neiljerram They are, but eventlet does something a little naughty by adding itself ahead of the standard library in the `sys.path` which makes our code which runs `import select` choose eventlet's `select.py` over the standard library. It's what makes it so you can run eventlet without needing to write `from eventlet.green import os` instead you just write `import os`.

I believe this is what is happening? I could be wrong, I don't have much eventlet experience.

**Comment by SethMichaelLarson** [comment]
@neiljerram Are you by-chance calling `eventlet.monkey_patch()` in your project?

**Comment by Lukasa** [comment]
I guarantee that this is identical to kennethreitz/requests#3831.

**Comment by SethMichaelLarson** [comment]
@Lukasa Looks identical to me! I'll make a patch to make `selectors` behave better if we can detect that `select` is monkey patched.

**Comment by Lukasa** [comment]
Specifically, you must monkey patch before you import urllib3. urllib3 does import-time feature detection of selectors, and I bet that eventlet does what gevent does and deletes objects from the select module. That therefore must be done first.

**Comment by Lukasa** [comment]
I don't know that we need to consider this a urllib3 bug. I think that this is the rule of monkey patching: if you're going to delete things from modules, then you need to do that before you do literally anything else.

**Comment by SethMichaelLarson** [comment]
@Lukasa Doesn't have to be considered a bug, just quality of life fix?

**Comment by SethMichaelLarson** [comment]
@Lukasa Could this not be a one-time check on the first call to `DefaultSelector`? After that first call replaces itself with the actual selector implementation?

**Comment by Lukasa** [comment]
@SethMichaelLarson So we can delay like that, yeah, but that only moves the window of failure. *In general* we cannot be resilient against a monkeypatch after import time. I'm certainly ok with a patch that does lazy selection of the default selector, but if we didn't do that I also wouldn't lose any sleep over it. 😉

**Comment by SethMichaelLarson** [comment]
@Lukasa Of course! I'm just thinking that with the amount of issues that have been raised already this blind monkey patching issue probably isn't going to go away. I'll write up a patch tonight if I have time and see how it performs. :)

**Comment by neiljerram** [comment]
Thanks everyone, I'll see if I can establish if and when eventlet monkey patching is occurring, and move it earlier.

**Comment by neiljerram** [comment]
FYI, the change that I've tried to my app at [1] seems to be effective.  As you suggested above, it simply ensures that eventlet monkey patching is done before the first urllib3 import.

[1] https://review.openstack.org/#/c/425351/

**Comment by s251251251** [comment]
Hello all 
recently I install Swift (Openstack swift object storage) and it seems I have same problem. I install Swift with Keystone authentication on Ubuntu. TempAuth is working but when try to authenticate by keystone swift send back internal server error as follow:

Feb  7 13:43:36 shard1 proxy-server: Error: An error occurred: #012Traceback (most recent call last):#012  File "/usr/local/lib/python2.7/dist-packages/swift/common/middleware/catch_errors.py", line 41, in handle_request#012    resp = self._app_call(env)#012  File "/usr/local/lib/python2.7/dist-packages/swift/common/wsgi.py", line 1059, in _app_call#012    self._response_exc_info = None#012  File "/usr/local/lib/python2.7/dist-packages/swift/common/middleware/gatekeeper.py", line 102, in __call__#012    return self.app(env, gatekeeper_response)#012  File "/usr/local/lib/python2.7/dist-packages/swift/common/middleware/healthcheck.py", line 52, in __call__#012    return self.app(env, start_response)#012  File "/usr/local/lib/python2.7/dist-packages/swift/common/middleware/proxy_logging.py", line 346, in __call__#012    six.reraise(exc_type, exc_value, exc_traceback)#012  File "/usr/local/lib/python2.7/dist-packages/swift/common/middleware/proxy_logging.py", line 338, in __call__#012    iterable = self.app(env, my_start_response)#012  File "/usr/local/lib/python2.7/dist-packages/swift/common/middleware/memcache.py", line 109, in __call__#012    return self.app(env, start_response)#012  File "/usr/local/lib/python2.7/dist-packages/swift/common/swob.py", line 1402, in _wsgify_self#012    return func(self, Request(env))(env, start_response)#012  File "/usr/local/lib/python2.7/dist-packages/swift/common/swob.py", line 1402, in _wsgify_self#012    return func(self, Request(env))(env, start_response)#012  File "/usr/local/lib/python2.7/dist-packages/swift/common/middleware/tempurl.py", line 401, in __call__#012    return self.app(env, start_response)#012  File "/usr/local/lib/python2.7/dist-packages/swift/common/middleware/ratelimit.py", line 301, in __call__#012    return self.app(env, start_response)#012  File "/usr/local/lib/python2.7/dist-packages/swift/common/middleware/tempauth.py", line 293, in __call__#012    return self.app(env, start_response)#012  File "/usr/local/lib/python2.7/dist-packages/swift/common/middleware/copy.py", line 318, in __call__#012    return self.app(env, start_response)#012  File "/usr/local/lib/python2.7/dist-packages/swift/common/swob.py", line 1402, in _wsgify_self#012    return func(self, Request(env))(env, start_response)#012  File "/usr/local/lib/python2.7/dist-packages/swift/common/swob.py", line 1402, in _wsgify_self#012    return func(self, Request(env))(env, start_response)#012  File "/usr/local/lib/python2.7/dist-packages/swift/common/middleware/slo.py", line 1167, in __call__#012    return self.app(env, start_response)#012  File "/usr/local/lib/python2.7/dist-packages/swift/common/middleware/dlo.py", line 415, in __call__#012    return self.app(env, start_response)#012  File "/usr/local/lib/python2.7/dist-packages/swift/common/middleware/versioned_writes.py", line 802, in __call__#012    return self.app(env, start_response)#012  File "/usr/local/lib/python2.7/dist-packages/webob/dec.py", line 131, in __call__#012    resp = self.call_func(req, *args, **self.kwargs)#012  File "/usr/local/lib/python2.7/dist-packages/webob/dec.py", line 196, in call_func#012    return self.func(req, *args, **kwargs)#012  File "/usr/local/lib/python2.7/dist-packages/keystonemiddleware/auth_token/__init__.py", line 332, in __call__#012    response = self.process_request(req)#012  File "/usr/local/lib/python2.7/dist-packages/keystonemiddleware/auth_token/__init__.py", line 623, in process_request#012    resp = super(AuthProtocol, self).process_request(request)#012  File "/usr/local/lib/python2.7/dist-packages/keystonemiddleware/auth_token/__init__.py", line 405, in process_request#012    allow_expired=allow_expired)#012  File "/usr/local/lib/python2.7/dist-packages/keystonemiddleware/auth_token/__init__.py", line 435, in _do_fetch_token#012    data = self.fetch_token(token, **kwargs)#012  File "/usr/local/lib/python2.7/dist-packages/keystonemiddleware/auth_token/__init__.py", line 762, in fetch_token#012    allow_expired=allow_expired)#012  File "/usr/local/lib/python2.7/dist-packages/keystonemiddleware/auth_token/_identity.py", line 229, in verify_token#012    return self.verify_token(user_token, False)#012  File "/usr/local/lib/python2.7/dist-packages/keystonemiddleware/auth_token/_identity.py", line 217, in verify_token#012    auth_ref = self._request_strategy.verify_token(#012  File "/usr/local/lib/python2.7/dist-packages/keystonemiddleware/auth_token/_identity.py", line 168, in _request_strategy#012    strategy_class = self._get_strategy_class()#012  File "/usr/local/lib/python2.7/dist-packages/keystonemiddleware/auth_token/_identity.py", line 190, in _get_strategy_class#012    if self._adapter.get_endpoint(version=klass.AUTH_VERSION):#012  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/adapter.py", line 176, in get_endpoint#012    return self.session.get_endpoint(auth or self.auth, **kwargs)#012  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py", line 856, in get_endpoint#012    return auth.get_endpoint(self, **kwargs)#012  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/identity/base.py", line 212, in get_endpoint#012    service_catalog = self.get_access(session).service_catalog#012  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/identity/base.py", line 136, in get_access#012    self.auth_ref = self.get_auth_ref(session)#012  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/identity/generic/base.py", line 198, in get_auth_ref#012    return self._plugin.get_auth_ref(session, **kwargs)#012  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/identity/v3/base.py", line 167, in get_auth_ref#012    authenticated=False, log=False, **rkwargs)#012  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py", line 766, in post#012    return self.request(url, 'POST', **kwargs)#012  File "/usr/local/lib/python2.7/dist-packages/positional/__init__.py", line 101, in inner#012    return wrapped(*args, **kwargs)#012  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py", line 616, in request#012    resp = send(**kwargs)#012  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py", line 674, in _send_request#012    resp = self.session.request(method, url, **kwargs)#012  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request#012    resp = self.send(prep, **send_kwargs)#012  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send#012    r = adapter.send(request, **kwargs)#012  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 423, in send#012    timeout=timeout#012  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 588, in urlopen#012    conn = self._get_conn(timeout=pool_timeout)#012  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 241, in _get_conn#012    if conn and is_connection_dropped(conn):#012  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/connection.py", line 27, in is_connection_dropped#012    return bool(wait_for_read(sock, timeout=0.0))#012  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/wait.py", line 33, in wait_for_read#012    return _wait_for_io_events(socks, EVENT_READ, timeout)#012  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/wait.py", line 22, in _wait_for_io_events#012    with DefaultSelector() as selector:#012  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/selectors.py", line 364, in __init__#012    self._epoll = select.epoll()#012AttributeError: 'module' object has no attribute 'epoll' (txn: tx881fd518167b494789fe4-0058999dd0)

any idea. Thanks

**Comment by Lukasa** [comment]
@s251251251 The solution to your problem is likely identical to the solution that we gave the earlier poster in this issue (I'm avoiding tagging them to avoid email spam). Have you attempted that solution?

**Comment by s251251251** [comment]
I just confused about exactly what I must do in which file. 
as I got I must add this line after import 
import eventlet
eventlet.monkey_patch()
as I see in this https://review.openstack.org/#/c/425351/4/networking_calico/agent/dhcp_agent.py
But in my case I can not undrestand where I must put this line.

**Comment by Lukasa** [comment]
That understanding is not right. That line already exists. It must be *moved* to be before urllib3 is ever imported. [This patch](https://review.openstack.org/#/c/425351/) should be all you need to apply.

**Comment by s251251251** [comment]
Thanks.
This patch is for other openstack service(Networking) I am working on swift so I think I need other patch

**Comment by Lukasa** [comment]
Ok, the premise remains the same. Eventlet monkeypatching must *always* come before doing anything else, including importing other modules. If anywhere is doing eventlet monkeypatching, that needs to be hoisted all the way to the top of the execution tree, so that urllib3 is not imported before the monkeypatch is applied.

**Comment by sigmavirus24** [comment]
@s251251251 you should absolutely file a bug in LaunchPad with the swift team. They are *paid* to fix these issues for you.

**Comment by s251251251** [comment]
@neiljerram Would please let me know how you to find where must be placed monkey patching. Why you are putting it in dhcp_agent.py?? in swift cods i can not find any import eventlet. would please check my log and help me. Thanks

**Comment by sigmavirus24** [comment]
@s251251251 No one on this thread is paid to work on Swift. To contact the Swift developers you have three options:

1. [OpenStack Development Mailing List](http://lists.openstack.org/pipermail/openstack-dev/)
2. [Swift Bug Tracker](https://bugs.launchpad.net/swift)
3. `#openstack-swift` IRC Channel on Freenode IRC.

They are the people best suited to helping you determine how to fix this for Swift.

**Comment by s251251251** [comment]
Hi
The problem solved by putting following lines in  /usr/local/lib/python2.7/dist-packages/swift/proxy/server.py, However I do not know is it good place or not.

from gevent import monkey
monkey.patch_all()

I have reported this bug.
https://bugs.launchpad.net/swift/+bug/1662473

**Comment by Lothiraldan** [comment]
I encountered this error this week by updating urllib to 1.20. I am in a case where we are importing and doing some HTTP requests before gevent is even imported. (For details, I am executing code in a sitecustomize.py module before a gunicorn server starts a gevent worker).

It would be very difficult for me to delay our urllib calls after gevent has patched half of the world.

What would be the best way to manually relaunch the feature detection? I tried playing with `reload` but without luck. Would it be possible to have something like that:

In the file selectors.py:
```
def get_selector():
    if hasattr(select, "kqueue"):
        return KqueueSelector
    elif hasattr(select, "epoll"):
        return SelectSelector
    ...


DefaultSelector = get_selector()
```

This way if someone need to manually redo the feature selection he can do:
```
import urllib3.util.wait
import urllib3.util.selectors

urllib3.util.wait.DefaultSelector = import urllib3.util.selectors.get_selector()
```

I'm aware that this exact solution is kind of ugly but maybe we can find a better solution.

**Comment by Lukasa** [comment]
@Lothiraldan Please see #1128 for a proposed fix.

**Comment by SethMichaelLarson** [comment]
Hello all, #1128 has been merged. Please test the latest if you can GitHub version if you have time and report back. :tada:

**Comment by sigmavirus24** [comment]
@SethMichaelLarson worth noting that some people on this thread will require an updated version of Requests to test this (e.g., 2.14.0 of Requests)

**Comment by neiljerram** [comment]
I believe this issue can be closed now.  The immediate problem was fixed in my networking-calico project by doing

    import eventlet
    eventlet.monkey_patch

as early as possible, and IIUC there also upstream improvements to eventlet/urllib3/requests to prevent this from being a problem in future releases.
