### ISSUE TITLE
Chunked responses lack data

### ISSUE THREAD

**Issue by mwitkow-io** [shazow/urllib3#654]
Using urllib3 1.10.3 in python-etcd client.

We were hitting a really weird bug when occasonally we'd get 

```python
Traceback (most recent call last):
  File "etcd/lib_etcd.py", line 116, in _result_from_response
    res = json.loads(response.data.decode('utf-8'))
  File "~/soft/infra-virtenv/local/lib/python2.7/site-packages/urllib3/response.py", line 166, in data
    return self.read(cache_content=True)
  File "~/infra-virtenv/local/lib/python2.7/site-packages/urllib3/response.py", line 239, in read
    data = self._fp.read()
  File "/usr/lib/python2.7/httplib.py", line 549, in read
    return self._read_chunked(amt)
  File "/usr/lib/python2.7/httplib.py", line 622, in _read_chunked
    self._safe_read(2)      # toss the CRLF at the end of the chunk
  File "/usr/lib/python2.7/httplib.py", line 664, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
AttributeError: 'NoneType' object has no attribute 'read'
```

on a chunked response from Etcd. 

It seems to be related to the fact that `HttpConectionPool#urlopen` by default `release_conn=True`, which is dictated by `preload_content`
```python
~/soft/infra-virtenv/lib/python2.7/site-packages/urllib3/connectionpool.py:510
        if release_conn is None:
            release_conn = response_kw.get('preload_content', True)
```

which means that if it is a chunked response, it will be closed immediately without the requesting library being able to read the content, since
```python
~/soft/infra-virtenv/lib/python2.7/site-packages/urllib3/response.py:135
        # We certainly don't want to preload content when the response is chunked.
        if not self.chunked and preload_content and not self._body:
            self._body = self.read(decode_content=decode_content)
```

This is fine, as long as the connection doesn't get reused, but under heavy load it causes things to break really badly.

**Comment by shazow** [comment]
@mwitkow-io Can you give the latest master a try? We should have fixed this in #647.

**Comment by mwitkow-io** [comment]
Apologies for this long delay, indeed the master fixed if for us.

**Comment by M4rtinK** [comment]
Is this supposed to be fixed in 1.11 ? Because I'm still occasionally getting it with that version:


```
Traceback (most recent call last):
  File "modules/mod_mapTiles/tile_downloader.py", line 126, in _handleDownload
    self._downloadTile(lzxy)
  File "modules/mod_mapTiles/tile_downloader.py", line 169, in _downloadTile
    content = self._mapTiles._downloadTile(lzxy)
  File "modules/mod_mapTiles/mod_mapTiles.py", line 245, in _downloadTile
    tileData = response.data
  File "/usr/lib/python3.4/site-packages/urllib3/response.py", line 166, in data
    return self.read(cache_content=True)
  File "/usr/lib/python3.4/site-packages/urllib3/response.py", line 239, in read
    data = self._fp.read()
  File "/usr/lib64/python3.4/http/client.py", line 506, in read
    return self._readall_chunked()
  File "/usr/lib64/python3.4/http/client.py", line 595, in _readall_chunked
    self._safe_read(2)      # toss the CRLF at the end of the chunk
  File "/usr/lib64/python3.4/http/client.py", line 662, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
AttributeError: 'NoneType' object has no attribute 'read'
```
Example of an occasionally affected URL:
http://tiles2.openpistemap.org/landshaded/13/4494/2803.png

**Comment by sigmavirus24** [comment]
@M4rtinK that's correct. It's documented as being fixed in 1.11.

**Comment by russ0519** [comment]
I'm getting this on 1.12

**Comment by russ0519** [comment]
I'm still getting it in 1.12

`AttributeError("'NoneType' object has no attribute 'read'",)
  File "/usr/lib/python2.6/site-packages/urllib3/response.py", line 164, in data
    return self.read(cache_content=True)
  File "/usr/lib/python2.6/site-packages/urllib3/response.py", line 292, in read
    flush_decoder = True
  File "/usr/lib64/python2.6/contextlib.py", line 34, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.6/site-packages/urllib3/response.py", line 214, in _error_catcher
    yield
  File "/usr/lib/python2.6/site-packages/urllib3/response.py", line 278, in read
    data = self._fp.read()
  File "/usr/lib64/python2.6/httplib.py", line 522, in read
    return self._read_chunked(amt)
  File "/usr/lib64/python2.6/httplib.py", line 569, in _read_chunked
    value.append(self._safe_read(chunk_left))
  File "/usr/lib64/python2.6/httplib.py", line 619, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
`

**Comment by Lukasa** [comment]
How reproducible is it?

**Comment by russ0519** [comment]
It happens a lot (with 10 threads) with 1.11 and 1.12.  

It seems to work fine on <1.11.

**Comment by Lukasa** [comment]
I'm not enormously surprised by that: I suspect it's the fault of our custom chunked encoding code. Out of interest, do you have a way for me to configure a repro scenario? It'll be easiest if I can dive into the code and chase this myself.

**Comment by russ0519** [comment]
I am hitting a Google api that requires a key.  If you have another url
that you think would exhibit the same behavior, I can try to make a repro.

**Comment by Lukasa** [comment]
@russ0519 I think that's my point: thus far, I haven't seen a repro, so I don't really know what the common factors are. You could try `httpbin.org/stream/100`, which will send chunked encoded responses, but I have no idea if that's the problem or not.

**Comment by ligthyear** [comment]
@Lukasa not exactly sure it is the same problem (as we see different error messages) but I am able to relyable reproduce a problem here caused by chunked encoding:

https://github.com/shazow/urllib3/compare/master...ligthyear:add-transfer-encoding-header-to-tests

Just adding the headers to the dummy-server makes the tests stall forever on python 2.7.10 (via Mac Homebrew – don't ask!):

![screen shot 2016-05-18 at 11 28 00](https://cloud.githubusercontent.com/assets/40496/15353954/ab8adf40-1ceb-11e6-9c49-5e15838a18ca.png)




---

Background: I ran into that as pycouchdb uses requests, which uses urllib3 internally and connecting to couchdb we saw a lot of "BadStatusLine"-Errors, which appear to stem from the fact that couchdb sends a lot of content in chunked transfer mode and the urllib3 connection pool puts them back into the pool long before their content has been read – causing the following request to hick up, when reading old content believing to be part of its own response and having trouble parsing that.

I was trying to make a test case for that when I noticed that none of the existing "chunk"-dummy-server-tests actually send the header (or its length), which appears to be already enough to cause a major problem for urllib3 on python2.7 (.10). I appreciate any input on the matter.

**Comment by Lukasa** [comment]
Uh..those headers are wrong. You can't send `Transfer-Encoding: chunked` *and* `Content-Length`. That makes me wonder about what exactly the dummyserver is doing in that case.

**Comment by ligthyear** [comment]
Well, according to the [spec is okay to send both](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.4) the latest just should be ignored by a client. However, that really isn't the issue. It was an attempt to fix the problem at hand. Removing it (as I did in the updated result just now) still causes the same forever-stalling...

**Comment by Lukasa** [comment]
RFC 2616 is not the specification for HTTP/1.1, RFC 7230 is. RFC 7230 says [you cannot send both](https://tools.ietf.org/html/rfc7230#section-3.3.2):

> A sender MUST NOT send a Content-Length header field in any message that contains a Transfer-Encoding header field.

It's good to know that removing it causes the same problem though. Let me see if I can adequately reproduce it locally.

**Comment by Lukasa** [comment]
Ok, so some quick debugging turns out the result.

You do not need to set `Transfer-Encoding: chunked` from the headers directly: Tornado sets it automatically. If you *do* set it manually, for some reason Tornado decides *not* to chunk the body and instead writes it in non-chunked form. That leads requests/urllib3 to sit there waiting for a chunk delimiter that is never coming. So the test scenario you're hitting is where a server reports chunked transfer encoding but doesn't actually send it. The hang would be shorter if you set a timeout, because requests/urllib3 will give up waiting.

So, this is not a bug: the change to the server is invalid.

**Comment by ligthyear** [comment]
@Lukasa thanks for debugging and thanks for reporting back. I appreciate it. I can confirm removing that header makes them work fine. Tornado is truly acting weird...

Meanwhile, I am having trouble reproducing the actual problem via a test case. The dummy server doesn't handle concurrent connections now, does it? I have a test case with multiple threads fetching and reading but they seem to be handled sequentially by the server, not triggering the issue we are having with our couchdb...

**Comment by Lukasa** [comment]
The dummy server should handle multiple concurrent connections, being written in Tornado. As far as I know it doesn't require any kind of synchronous execution.
